function videotile(num)
if num == 36
    system(['ffmpeg ' ...
       '-i videos/1.avi ' ...
       '-i videos/2.avi ' ...
       '-i videos/3.avi ' ...
       '-i videos/4.avi ' ...
       '-i videos/5.avi ' ...
       '-i videos/6.avi ' ...
       '-i videos/7.avi ' ...
       '-i videos/8.avi ' ...
       '-i videos/9.avi ' ...
       '-i videos/10.avi ' ...
       '-i videos/11.avi ' ...
       '-i videos/12.avi ' ...
       '-i videos/13.avi ' ...
       '-i videos/14.avi ' ...
       '-i videos/15.avi ' ...
       '-i videos/16.avi ' ...
       '-i videos/17.avi ' ...
       '-i videos/18.avi ' ...
       '-i videos/19.avi ' ...
       '-i videos/20.avi ' ...
       '-i videos/21.avi ' ...
       '-i videos/22.avi ' ...
       '-i videos/23.avi ' ...
       '-i videos/24.avi ' ...
       '-i videos/25.avi ' ...
       '-i videos/26.avi ' ...
       '-i videos/27.avi ' ...
       '-i videos/28.avi ' ...
       '-i videos/29.avi ' ...
       '-i videos/30.avi ' ...
       '-i videos/31.avi ' ...
       '-i videos/32.avi ' ...
       '-i videos/33.avi ' ...
       '-i videos/34.avi ' ...
       '-i videos/35.avi ' ...
       '-i videos/36.avi ' ...
       '-filter_complex " ' ...
          '[0:v] setpts=PTS-STARTPTS, scale=qqvga [a0]; ' ...
          '[1:v] setpts=PTS-STARTPTS, scale=qqvga [a1]; ' ...
          '[2:v] setpts=PTS-STARTPTS, scale=qqvga [a2]; ' ...
          '[3:v] setpts=PTS-STARTPTS, scale=qqvga [a3]; ' ...
          '[4:v] setpts=PTS-STARTPTS, scale=qqvga [a4]; ' ...
          '[5:v] setpts=PTS-STARTPTS, scale=qqvga [a5]; ' ...
          '[6:v] setpts=PTS-STARTPTS, scale=qqvga [a6]; ' ...
          '[7:v] setpts=PTS-STARTPTS, scale=qqvga [a7]; ' ...
          '[8:v] setpts=PTS-STARTPTS, scale=qqvga [a8]; ' ...
          '[9:v] setpts=PTS-STARTPTS, scale=qqvga [a9]; ' ...
          '[10:v] setpts=PTS-STARTPTS, scale=qqvga [a10]; ' ...
          '[11:v] setpts=PTS-STARTPTS, scale=qqvga [a11]; ' ...
          '[12:v] setpts=PTS-STARTPTS, scale=qqvga [a12]; ' ...
          '[13:v] setpts=PTS-STARTPTS, scale=qqvga [a13]; ' ...
          '[14:v] setpts=PTS-STARTPTS, scale=qqvga [a14]; ' ...
          '[15:v] setpts=PTS-STARTPTS, scale=qqvga [a15]; ' ...
          '[16:v] setpts=PTS-STARTPTS, scale=qqvga [a16]; ' ...
          '[17:v] setpts=PTS-STARTPTS, scale=qqvga [a17]; ' ...
          '[18:v] setpts=PTS-STARTPTS, scale=qqvga [a18]; ' ...
          '[19:v] setpts=PTS-STARTPTS, scale=qqvga [a19]; ' ...
          '[20:v] setpts=PTS-STARTPTS, scale=qqvga [a20]; ' ...
          '[21:v] setpts=PTS-STARTPTS, scale=qqvga [a21]; ' ...
          '[22:v] setpts=PTS-STARTPTS, scale=qqvga [a22]; ' ...
          '[23:v] setpts=PTS-STARTPTS, scale=qqvga [a23]; ' ...
          '[24:v] setpts=PTS-STARTPTS, scale=qqvga [a24]; ' ...
          '[25:v] setpts=PTS-STARTPTS, scale=qqvga [a25]; ' ...
          '[26:v] setpts=PTS-STARTPTS, scale=qqvga [a26]; ' ...
          '[27:v] setpts=PTS-STARTPTS, scale=qqvga [a27]; ' ...
          '[28:v] setpts=PTS-STARTPTS, scale=qqvga [a28]; ' ...
          '[29:v] setpts=PTS-STARTPTS, scale=qqvga [a29]; ' ...
          '[30:v] setpts=PTS-STARTPTS, scale=qqvga [a30]; ' ...
          '[31:v] setpts=PTS-STARTPTS, scale=qqvga [a31]; ' ...
          '[32:v] setpts=PTS-STARTPTS, scale=qqvga [a32]; ' ...
          '[33:v] setpts=PTS-STARTPTS, scale=qqvga [a33]; ' ...
          '[34:v] setpts=PTS-STARTPTS, scale=qqvga [a34]; ' ...
          '[35:v] setpts=PTS-STARTPTS, scale=qqvga [a35]; ' ...
          '[a0][a1][a2][a3][a4][a5][a6][a7][a8][a9][a10][a11][a12][a13][a14][a15][a16][a17][a18][a19][a20][a21][a22][a23][a24][a25][a26][a27][a28][a29][a30][a31][a32][a33][a34][a35]xstack=inputs=36:layout=0_0|w0_0|w0+w1_0|w0+w1+w2_0|w0+w1+w2+w3_0|w0+w1+w2+w3+w4_0|0_h0|w0_h0|w0+w1_h0|w0+w1+w2_h0|w0+w1+w2+w3_h0|w0+w1+w2+w3+w4_h0|0_h0+h1|w0_h0+h1|w0+w1_h0+h1|w0+w1+w2_h0+h1|w0+w1+w2+w3_h0+h1|w0+w1+w2+w3+w4_h0+h1|0_h0+h1+h2|w0_h0+h1+h2|w0+w1_h0+h1+h2|w0+w1+w2_h0+h1+h2|w0+w1+w2+w3_h0+h1+h2|w0+w1+w2+w3+w4_h0+h1+h2|0_h0+h1+h2+h3|w0_h0+h1+h2+h3|w0+w1_h0+h1+h2+h3|w0+w1+w2_h0+h1+h2+h3|w0+w1+w2+w3_h0+h1+h2+h3|w0+w1+w2+w3+w4_h0+h1+h2+h3|0_h0+h1+h2+h3+h4|w0_h0+h1+h2+h3+h4|w0+w1_h0+h1+h2+h3+h4|w0+w1+w2_h0+h1+h2+h3+h4|w0+w1+w2+w3_h0+h1+h2+h3+h4|w0+w1+w2+w3+w4_h0+h1+h2+h3+h4[out] ' ...
          '" ' ...
        '-map "[out]" ' ...
        '-c:v mjpeg -q:v 1 out.avi']);
elseif num == 9
    system(['ffmpeg ' ...
   '-i videos/1.avi ' ...
   '-i videos/2.avi ' ...
   '-i videos/3.avi ' ...
   '-i videos/4.avi ' ...
   '-i videos/5.avi ' ...
   '-i videos/6.avi ' ...
   '-i videos/7.avi ' ...
   '-i videos/8.avi ' ...
   '-i videos/9.avi ' ...
   '-filter_complex " ' ...
      '[0:v] setpts=PTS-STARTPTS, scale=qvga [a0]; ' ...
      '[1:v] setpts=PTS-STARTPTS, scale=qvga [a1]; ' ... 
      '[2:v] setpts=PTS-STARTPTS, scale=qvga [a2]; ' ...
      '[3:v] setpts=PTS-STARTPTS, scale=qvga [a3]; ' ...
      '[4:v] setpts=PTS-STARTPTS, scale=qvga [a4]; ' ...
      '[5:v] setpts=PTS-STARTPTS, scale=qvga [a5]; ' ...
      '[6:v] setpts=PTS-STARTPTS, scale=qvga [a6]; ' ...
      '[7:v] setpts=PTS-STARTPTS, scale=qvga [a7]; ' ...
      '[8:v] setpts=PTS-STARTPTS, scale=qvga [a8]; ' ...
      '[a0][a1][a2][a3][a4][a5][a6][a7][a8]xstack=inputs=9:layout=0_0|w0_0|w0+w1_0|0_h0|w0_h0|w0+w1_h0|0_h0+h1|w0_h0+h1|w0+w1_h0+h1[out] '...
      '" \'...
      '-map "[out]" \'...
      '-c:v mjpeg -q:v 1 out.avi']);
end